name: Atlas POST via http request
on:
    push:
        branches: [ "master", "app1", "app2", "app3" ]
jobs:
    prepare-response:
        runs-on: ubuntu-latest
        outputs:
            response-made: ${{ steps.find-one.outputs.response}}
        steps:
        -   name: Find one
            id: find-one 
            uses: fjogeleit/http-request-action@v1
            with:
                url: 'https://data.mongodb-api.com/app/data-qbtmk/endpoint/data/v1/action/findOne'
                method: 'POST'
                customHeaders: '{"Content-Type": "application/json", "Access-Control-Request-Headers": "*", "api-key": "ss4YLpyU2RNqHXP00VxIlwi9nMJpxLGC0E1FCmlBgFclysZyTwgxx3jipuG0pdqJ"}'
                data: '{ "collection":"evault", "database":"fiserv", "dataSource":"sandbox", "projection": {"_id": 0}}'
        -   name: Show Response
            run: |
                echo 'response: ${{ steps.find-one.outputs.response }}'
                echo 'header: ${{ steps.find-one.outputs.headers }}'
                echo 'email: ${{ steps.find-one.outputs.response.email}}'
# echo ${{ fromJson(steps.find-one.outputs.response).email}}

    confirm-response:
        needs: prepare-response
        runs-on: ubuntu-latest
        strategy:
            matrix:
                file: ${{ fromJson(needs.prepare-response.outputs.response-made) }}
        steps:
        -   name: Checkout
            uses: actions/checkout@v3
        
        -   name: Echo file
            run: |
                echo ${{ matrix.file }} # to test if the correct file was passed

# jobs:
#     deployment:
#       runs-on: ubuntu-latest
#       steps:
#       - name: Deploy Stage
#         uses: fjogeleit/http-request-action@v1
#         with:
#           url: 'https://data.mongodb-api.com/app/data-qbtmk/endpoint/data/v1/action/findOne'
#           method: 'POST'
#           username: ${{ secrets.AWX_USER }}
#           password: ${{ secrets.AWX_PASSWORD }}
#           customHeaders: '{"Content-Type": "application/json"}'
#           data: '{"key_1": "value_1", "key_2": "value_2"}'

# jobs:
#     deployment:
#       runs-on: ubuntu-latest
#       steps:
#       - name: Deploy Stage
#         uses: fjogeleit/http-request-action@v1
#         with:
#           url: 'https://data.mongodb-api.com/app/data-qbtmk/endpoint/data/v1/action/findOne'
#           method: 'POST'
#           username: ${{ secrets.AWX_USER }}
#           password: ${{ secrets.AWX_PASSWORD }}
#           customHeaders: '{"Content-Type": "application/json", "Access-Control-Request-Headers": "*", "api-key": "ss4YLpyU2RNqHXP00VxIlwi9nMJpxLGC0E1FCmlBgFclysZyTwgxx3jipuG0pdqJ", "Accept": "application/ejson"}'
#           data: '{ "collection":"devstudio", "database":"fiserv", "dataSource":"sandbox", "projection": {"_id": 1}}'

# curl --location --request POST 'https://data.mongodb-api.com/app/data-qbtmk/endpoint/data/v1/action/findOne' \
# --header 'Content-Type: application/json' \
# --header 'Access-Control-Request-Headers: *' \
# --header 'api-key: ss4YLpyU2RNqHXP00VxIlwi9nMJpxLGC0E1FCmlBgFclysZyTwgxx3jipuG0pdqJ' \
# --data-raw '{
#     "collection":"devstudio",
#     "database":"fiserv",
#     "dataSource":"sandbox",
#     "projection": {"_id": 1}
# }'
          